import type { PathLike } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const GENERATED_WORKFLOW_MARKER = '# Generated by: release-it-preset init --with-workflows'

const WORKFLOW_TEMPLATE_RELATIVE_PATH = ['workflows', 'release.yml.template'] as const

export interface WorkflowTemplateDeps {
  existsSync: (path: PathLike) => boolean
  readFileSync: (path: PathLike, encoding: BufferEncoding) => string | Buffer
}

export interface WorkflowTemplateReadResult {
  path: string
  content: string
}

export function getWorkflowTemplateCandidates(moduleUrl = import.meta.url): string[] {
  const moduleDir = dirname(fileURLToPath(moduleUrl))

  return [
    join(moduleDir, '..', 'templates', ...WORKFLOW_TEMPLATE_RELATIVE_PATH),
    join(moduleDir, '..', '..', '..', 'scripts', 'templates', ...WORKFLOW_TEMPLATE_RELATIVE_PATH),
  ]
}

export function readWorkflowTemplate(
  deps: WorkflowTemplateDeps,
  moduleUrl = import.meta.url,
): WorkflowTemplateReadResult {
  const candidates = getWorkflowTemplateCandidates(moduleUrl)
  const templatePath = candidates.find((candidate) => deps.existsSync(candidate)) ?? candidates[0]

  try {
    return {
      path: templatePath,
      content: deps.readFileSync(templatePath, 'utf8') as string,
    }
  } catch (error) {
    throw new Error(
      [
        `Failed to read workflow template at "${templatePath}".`,
        'The template ships in scripts/templates/ — if it is missing, reinstall the package.',
        `Original error: ${error}`,
      ].join('\n'),
    )
  }
}

export function hasGeneratedWorkflowMarker(content: string): boolean {
  return content.includes(GENERATED_WORKFLOW_MARKER)
}

export function normalizeWorkflowContent(content: string): string {
  return content.replace(/\r\n/g, '\n').replace(/\r/g, '\n').replace(/\n*$/, '\n')
}
