name: Hotfix Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version increment type'
        required: true
        type: choice
        options:
          - patch
          - minor
        default: patch
      commit:
        description: 'Specific commit SHA (optional, defaults to latest)'
        required: false
        type: string
      dry_run:
        description: 'Dry run (no actual release)'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit || github.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check TypeScript compilation
        run: pnpm tsc --noEmit

      - name: Build compiled scripts
        run: pnpm build

  hotfix:
    name: Create Hotfix Release
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit || github.sha }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Configure npm authentication
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Display hotfix information
        run: |
          echo "🚨 Hotfix Release Information"
          echo "============================="
          echo "Increment: ${{ inputs.increment }}"
          echo "Commit: ${{ inputs.commit || github.sha }}"
          echo "Dry run: ${{ inputs.dry_run }}"
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Latest commit: $(git log -1 --oneline)"

      - name: Run hotfix release and publish
        run: |
          if [ "${{ inputs.dry_run }}" == "true" ]; then
            echo "🧪 Running in DRY RUN mode"
            node bin/cli.js hotfix --ci --increment ${{ inputs.increment }} --dry-run
          else
            echo "🚀 Running LIVE hotfix release and publish"
            node bin/cli.js hotfix --ci --increment ${{ inputs.increment }}
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_PUBLISH: 'true'      # ✅ Publish to npm with provenance
          GITHUB_RELEASE: 'true'   # ✅ Create GitHub Release

      - name: Display hotfix release and publish info
        if: inputs.dry_run == false
        run: |
          echo "✅ Hotfix release and publish completed successfully"
          echo "Version: $(node -p \"require('./package.json').version\")"
          echo "Tag: $(git describe --tags --abbrev=0)"
          echo "npm: https://www.npmjs.com/package/@oorabona/release-it-preset"
          echo "GitHub: https://github.com/${{ github.repository }}/releases/tag/$(git describe --tags --abbrev=0)"
